---
- name: Configure satty
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ satty_config_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add satty config file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/config.toml.j2"
        dest: "{{ satty_config_file }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
